# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "1497352180" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/modded/1497352180/items/{ItemId}.png" # The repository of the override.