# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "1702240229" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/modded/1702240229/items/{ItemId}.png" # The repository of the override.