# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "2459189599" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/modded/2459189599/items/{ItemId}.png" # The repository of the override.