# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "1411633953" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/modded/1411633953/items/{ItemId}.png" # The repository of the override.